name: deploy lightsail
on:
  push:
    tags:
      - v**

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: build app
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/v##g")
          go build -ldflags="-X main.version=$VERSION" -o $GITHUB_WORKSPACE/bin/discobot

      - name: ssh key generate
        run: echo "$SSH_KEY" > key && chmod 600 key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: rsync deploy
        run: rsync -acvz -e "ssh -i key -o StrictHostKeyChecking=no" $GITHUB_WORKSPACE/bin/ ubuntu@54.238.207.235:/home/ubuntu/bin/

      - name: service restart
        run: ssh -o StrictHostKeyChecking=no ubuntu@54.238.207.235 -i key "sudo systemctl restart discobot"
